name: build

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: "retrieve pgeth"
        run: git clone https://github.com/mortimr/pgeth /tmp/pgeth
      - name: "build docker image with embedded plugin"
        run: cd /tmp/pgeth && docker build -f ./Dockerfile.plugins . --build-arg PLUGIN_REPOSITORIES="https://github.com/mortimr/pgeth-monitoring"
